[project]
name = "utilities"
version = "0.1.0"
description = "General utilities for Mikaelkirken and related projects"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "segno>=1.6.6",
    "openpyxl>=3.1.0",
]

# HER: Registrer nye terminalkommandoer
[project.scripts]
generate-qr = "utilities.qr:cli_main"
convert-pdf = "utilities.pdf:cli_convert_to_pdf"
merge-odt = "utilities.merge:cli_merge_odt"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
